# -*- coding: utf-8 -*-
"""Biblioteca de 150 ejercicios (seed, F.3).

Convenciones de valores (decisión declarada — slugs en castellano porque son
datos de cara al cliente en checklists, planes y gráficas):

- muscle_*: pecho, espalda, hombros, biceps, triceps, cuadriceps, isquios,
  gluteos, gemelos, core, antebrazos, trapecio, aductores
- movement_pattern (snake_case inglés, taxonomía técnica): horizontal_push,
  vertical_push, horizontal_pull, vertical_pull, squat, hip_hinge, lunge,
  knee_extension, knee_flexion, hip_extension, hip_abduction, hip_adduction,
  plantar_flexion, dorsiflexion, elbow_flexion, elbow_extension,
  shoulder_abduction, shoulder_flexion, shoulder_external_rotation,
  scapular_elevation, core_anti_extension, core_anti_rotation, core_flexion
- equipment: barra, mancuernas, maquina, polea, multipower, peso_corporal,
  banco, barra_dominadas, paralelas, bandas, kettlebell, barra_ez,
  barra_hexagonal, rack, disco, deslizadores, cajon, banco_scott, lastre
- contraindications (articulación sensible): hombro, codo, muneca, lumbar,
  rodilla, cadera, cuello, tobillo
- level_min: 1 principiante · 2 intermedio · 3 avanzado
- video_url: vacío por defecto, editable por el coach desde Settings (F.3)
"""

VALID_MUSCLES = {
    "pecho", "espalda", "hombros", "biceps", "triceps", "cuadriceps", "isquios",
    "gluteos", "gemelos", "core", "antebrazos", "trapecio", "aductores",
}
VALID_PATTERNS = {
    "horizontal_push", "vertical_push", "horizontal_pull", "vertical_pull",
    "squat", "hip_hinge", "lunge", "knee_extension", "knee_flexion",
    "hip_extension", "hip_abduction", "hip_adduction", "plantar_flexion",
    "dorsiflexion", "elbow_flexion", "elbow_extension", "shoulder_abduction",
    "shoulder_flexion", "shoulder_external_rotation", "scapular_elevation",
    "core_anti_extension", "core_anti_rotation", "core_flexion",
}
VALID_EQUIPMENT = {
    "barra", "mancuernas", "maquina", "polea", "multipower", "peso_corporal",
    "banco", "barra_dominadas", "paralelas", "bandas", "kettlebell", "barra_ez",
    "barra_hexagonal", "rack", "disco", "deslizadores", "cajon", "banco_scott",
    "lastre",
}
VALID_CONTRA = {"hombro", "codo", "muneca", "lumbar", "rodilla", "cadera", "cuello", "tobillo"}


def _ex(name, aliases, mp, ms, pattern, equip, lvl, tech, bio, contra):
    return {
        "canonical_name": name,
        "aliases": aliases,
        "muscle_primary": mp,
        "muscle_secondary": ms,
        "movement_pattern": pattern,
        "equipment": equip,
        "level_min": lvl,
        "video_url": "",
        "technique_notes": tech,
        "biomechanics_notes": bio,
        "contraindications": contra,
    }


EXERCISES = [
    # ================= EMPUJE HORIZONTAL (15) =================
    _ex("Press banca con barra", ["press de banca", "bench press", "press plano"],
        "pecho", ["triceps", "hombros"], "horizontal_push", ["barra", "banco", "rack"], 1,
        "Escápulas retraídas, pies firmes, barra a la línea del pecho bajo.",
        "El arco torácico estabiliza el hombro y alinea las fibras del pectoral con el empuje.",
        ["hombro"]),
    _ex("Press banca inclinado con barra", ["press inclinado", "incline bench press"],
        "pecho", ["hombros", "triceps"], "horizontal_push", ["barra", "banco", "rack"], 1,
        "Banco a 30-45°, la barra baja a la clavícula sin rebotar.",
        "La inclinación orienta la resistencia hacia las fibras claviculares del pectoral.",
        ["hombro"]),
    _ex("Press banca declinado con barra", ["press declinado", "decline bench press"],
        "pecho", ["triceps"], "horizontal_push", ["barra", "banco", "rack"], 2,
        "Recorrido corto y controlado, la barra toca el pecho bajo.",
        "El declive enfatiza la porción esternocostal y reduce el estrés del hombro.",
        []),
    _ex("Press banca con mancuernas", ["press plano con mancuernas", "dumbbell bench press"],
        "pecho", ["triceps", "hombros"], "horizontal_push", ["mancuernas", "banco"], 1,
        "Baja hasta un estiramiento cómodo, codos a unos 45° del torso.",
        "Las mancuernas permiten mayor rango y trabajo estabilizador que la barra.",
        ["hombro"]),
    _ex("Press inclinado con mancuernas", ["incline dumbbell press"],
        "pecho", ["hombros", "triceps"], "horizontal_push", ["mancuernas", "banco"], 1,
        "Banco a 30°, muñecas neutras, junta las mancuernas arriba sin chocarlas.",
        "Gran estiramiento del pectoral superior bajo carga: estímulo hipertrófico clave.",
        ["hombro"]),
    _ex("Press de pecho en máquina", ["chest press", "press en máquina"],
        "pecho", ["triceps", "hombros"], "horizontal_push", ["maquina"], 1,
        "Ajusta el asiento para que los agarres queden a media altura del pecho.",
        "La trayectoria guiada permite cercanía al fallo con riesgo mínimo.",
        []),
    _ex("Press banca en multipower", ["press banca smith"],
        "pecho", ["triceps", "hombros"], "horizontal_push", ["multipower", "banco"], 1,
        "Coloca el banco para que la barra baje a la línea del pecho bajo.",
        "La guía vertical elimina la estabilización: útil para fatigar con seguridad.",
        ["hombro"]),
    _ex("Press inclinado en multipower", ["press inclinado smith"],
        "pecho", ["hombros", "triceps"], "horizontal_push", ["multipower", "banco"], 1,
        "Banco a 30-45° centrado bajo la barra, baja a la clavícula.",
        "Trayectoria fija que estandariza el estímulo del pectoral superior serie a serie.",
        ["hombro"]),
    _ex("Flexiones", ["push ups", "lagartijas", "fondos en el suelo"],
        "pecho", ["triceps", "hombros", "core"], "horizontal_push", ["peso_corporal"], 1,
        "Cuerpo en línea recta, manos algo más anchas que los hombros.",
        "Empuje en cadena cerrada con escápulas libres: protracción completa arriba.",
        ["muneca"]),
    _ex("Flexiones lastradas", ["push ups con lastre", "flexiones con peso"],
        "pecho", ["triceps", "hombros", "core"], "horizontal_push", ["peso_corporal", "lastre"], 2,
        "Disco centrado en la espalda alta o chaleco; mismo cuerpo rígido.",
        "Permite sobrecarga progresiva manteniendo el patrón de cadena cerrada.",
        ["muneca"]),
    _ex("Fondos en paralelas (énfasis pecho)", ["dips pecho", "fondos pecho"],
        "pecho", ["triceps", "hombros"], "horizontal_push", ["paralelas"], 2,
        "Torso inclinado adelante, baja hasta sentir estiramiento sin dolor.",
        "La inclinación del torso desplaza la demanda del tríceps al pectoral inferior.",
        ["hombro"]),
    _ex("Aperturas con mancuernas", ["flyes", "aperturas planas"],
        "pecho", [], "horizontal_push", ["mancuernas", "banco"], 1,
        "Codos semiflexionados fijos, abre hasta estiramiento cómodo.",
        "Aísla la aducción horizontal: máxima tensión en estiramiento, controla la bajada.",
        ["hombro"]),
    _ex("Cruce de poleas", ["crossover", "cruces en polea", "cable fly"],
        "pecho", [], "horizontal_push", ["polea"], 1,
        "Paso adelante, abraza un árbol imaginario, junta manos al frente.",
        "La polea mantiene tensión constante también en el acortamiento máximo.",
        []),
    _ex("Contractora de pecho", ["pec deck", "peck deck", "mariposa"],
        "pecho", [], "horizontal_push", ["maquina"], 1,
        "Codos a la altura del pecho, junta y aprieta 1 segundo.",
        "Aducción horizontal guiada: aislamiento del pectoral sin demanda de estabilidad.",
        []),
    _ex("Press de suelo con barra", ["floor press"],
        "pecho", ["triceps"], "horizontal_push", ["barra", "rack"], 2,
        "Tumbado en el suelo, los codos tocan suavemente y empuja.",
        "El rango parcial limita la extensión del hombro: opción amable con hombros sensibles.",
        []),

    # ================= EMPUJE VERTICAL (10) =================
    _ex("Press militar de pie con barra", ["overhead press", "press militar", "ohp"],
        "hombros", ["triceps", "core"], "vertical_push", ["barra", "rack"], 2,
        "Glúteos y core firmes, la barra sube pegada a la cara y acaba sobre la coronilla.",
        "Empuje vertical global: el deltoides anterior lidera con gran demanda de core.",
        ["hombro", "lumbar"]),
    _ex("Press militar sentado con barra", ["press militar sentado"],
        "hombros", ["triceps"], "vertical_push", ["barra", "banco", "rack"], 2,
        "Respaldo casi vertical, antebrazos verticales bajo la barra.",
        "El apoyo elimina la extensión lumbar compensatoria y concentra el trabajo en el deltoides.",
        ["hombro"]),
    _ex("Press de hombros con mancuernas sentado", ["press militar con mancuernas", "shoulder press"],
        "hombros", ["triceps"], "vertical_push", ["mancuernas", "banco"], 1,
        "Codos ligeramente por delante del plano del torso, sube sin chocar arriba.",
        "El plano escapular (ligeramente frontal) es la trayectoria más amable para el manguito.",
        ["hombro"]),
    _ex("Press Arnold", ["arnold press"],
        "hombros", ["triceps"], "vertical_push", ["mancuernas", "banco"], 2,
        "Inicia con palmas hacia ti y rota mientras empujas hacia arriba.",
        "La rotación añade recorrido y solicita el deltoides anterior en mayor rango.",
        ["hombro"]),
    _ex("Press de hombros en máquina", ["shoulder press machine"],
        "hombros", ["triceps"], "vertical_push", ["maquina"], 1,
        "Ajusta el asiento: los agarres parten a la altura de las orejas.",
        "Guiado y estable: ideal para progresar cerca del fallo con técnica constante.",
        []),
    _ex("Press de hombros en multipower", ["press militar smith"],
        "hombros", ["triceps"], "vertical_push", ["multipower", "banco"], 1,
        "Banco casi vertical, la barra baja por delante hasta la barbilla.",
        "Trayectoria fija que permite cargar el empuje vertical sin estabilización.",
        ["hombro"]),
    _ex("Push press", ["press con empuje de piernas"],
        "hombros", ["triceps", "cuadriceps", "core"], "vertical_push", ["barra", "rack"], 3,
        "Pequeña flexión de rodillas y extiende explosivo transfiriendo a los brazos.",
        "El impulso de piernas permite sobrecargar la fase excéntrica del press.",
        ["hombro", "lumbar"]),
    _ex("Press landmine de pie", ["landmine press", "press con barra en esquina"],
        "hombros", ["pecho", "triceps", "core"], "vertical_push", ["barra"], 1,
        "Empuja la barra en diagonal hacia arriba y adelante, costillas abajo.",
        "El ángulo diagonal reduce la demanda de movilidad de hombro: ideal con limitaciones.",
        []),
    _ex("Flexiones pike", ["pike push ups", "flexiones en V"],
        "hombros", ["triceps"], "vertical_push", ["peso_corporal"], 2,
        "Cadera alta en V invertida, la cabeza baja entre las manos.",
        "Convierte la flexión en empuje casi vertical: progresión calisténica del press.",
        ["muneca", "hombro"]),
    _ex("Press de hombro unilateral con mancuerna de pie", ["press unilateral de hombro"],
        "hombros", ["triceps", "core"], "vertical_push", ["mancuernas"], 2,
        "Aprieta el glúteo del mismo lado y evita inclinarte al empujar.",
        "El empuje unilateral añade antiflexión lateral: hombro y core en un gesto.",
        ["hombro"]),

    # ================= TRACCIÓN HORIZONTAL (13) =================
    _ex("Remo con barra", ["barbell row", "remo inclinado"],
        "espalda", ["biceps", "trapecio", "isquios"], "horizontal_pull", ["barra"], 2,
        "Torso a 30-45°, lleva la barra al abdomen bajo sin dar tirones.",
        "Tracción horizontal global: dorsal y retractores escapulares con bisagra isométrica.",
        ["lumbar"]),
    _ex("Remo Pendlay", ["pendlay row"],
        "espalda", ["biceps", "trapecio"], "horizontal_pull", ["barra"], 3,
        "Torso paralelo al suelo, la barra parte del suelo en cada repetición.",
        "El reinicio desde el suelo elimina inercia y exige tracción explosiva estricta.",
        ["lumbar"]),
    _ex("Remo con mancuerna a una mano", ["remo unilateral", "one arm row"],
        "espalda", ["biceps"], "horizontal_pull", ["mancuernas", "banco"], 1,
        "Rodilla y mano apoyadas en el banco, tira del codo hacia la cadera.",
        "El apoyo descarga la lumbar y permite gran rango con sobrecarga unilateral.",
        []),
    _ex("Remo con pecho apoyado en banco", ["chest supported row", "remo tumbado en banco inclinado"],
        "espalda", ["biceps", "trapecio"], "horizontal_pull", ["mancuernas", "banco"], 1,
        "Pecho fijo al banco inclinado; tira de los codos atrás y junta escápulas.",
        "El apoyo elimina toda implicación lumbar: aislamiento real de la tracción.",
        []),
    _ex("Remo sentado en polea", ["remo en polea baja", "seated cable row", "remo gironda"],
        "espalda", ["biceps", "trapecio"], "horizontal_pull", ["polea"], 1,
        "Torso erguido estable, lleva el agarre al ombligo y junta escápulas.",
        "Tensión constante de la polea con torso fijo: técnica fácil de estandarizar.",
        []),
    _ex("Remo en máquina", ["remo hammer", "machine row"],
        "espalda", ["biceps", "trapecio"], "horizontal_pull", ["maquina"], 1,
        "Pecho apoyado en el pad, tira sin encoger los hombros hacia las orejas.",
        "Trayectoria guiada con apoyo torácico: progresión segura cerca del fallo.",
        []),
    _ex("Remo con barra T", ["t-bar row", "remo en punta"],
        "espalda", ["biceps", "trapecio", "isquios"], "horizontal_pull", ["barra", "maquina"], 2,
        "Agarre neutro, torso fijo a 45°, la carga sube al pecho bajo.",
        "El agarre neutro favorece la retracción y permite cargas altas de tracción.",
        ["lumbar"]),
    _ex("Remo invertido", ["inverted row", "remo australiano"],
        "espalda", ["biceps", "core"], "horizontal_pull", ["barra", "rack", "peso_corporal"], 1,
        "Cuerpo en tabla, lleva el pecho a la barra; más horizontal = más difícil.",
        "Tracción en cadena cerrada autorregulable por el ángulo del cuerpo.",
        []),
    _ex("Remo en polea a una mano", ["remo unilateral en polea"],
        "espalda", ["biceps"], "horizontal_pull", ["polea"], 1,
        "Permite rotar levemente el torso al tirar para alargar el dorsal.",
        "La tracción unilateral en polea maximiza el rango y corrige asimetrías.",
        []),
    _ex("Remo Meadows", ["meadows row"],
        "espalda", ["biceps", "trapecio"], "horizontal_pull", ["barra"], 3,
        "Perpendicular a la barra landmine, agarre por encima, tira hacia la cadera.",
        "El ángulo y el agarre pronado castigan dorsal alto y redondo mayor.",
        ["lumbar"]),
    _ex("Face pull en polea", ["face pull", "jalón a la cara"],
        "hombros", ["trapecio", "espalda"], "horizontal_pull", ["polea"], 1,
        "Cuerda a la altura de la cara, tira separando las manos hacia las orejas.",
        "Combina retracción y rotación externa: salud de hombro y deltoides posterior.",
        []),
    _ex("Pájaros con mancuernas", ["reverse fly", "aperturas invertidas", "bent over lateral raise"],
        "hombros", ["trapecio", "espalda"], "horizontal_pull", ["mancuernas"], 1,
        "Torso inclinado, codos semifijos, abre hacia los lados sin balanceo.",
        "Abducción horizontal pura: aísla deltoides posterior y trapecio medio.",
        ["lumbar"]),
    _ex("Contractora invertida", ["reverse pec deck", "peck deck invertido"],
        "hombros", ["trapecio", "espalda"], "horizontal_pull", ["maquina"], 1,
        "Pecho contra el pad, abre los brazos hasta la línea del torso.",
        "Aislamiento guiado del deltoides posterior sin implicación lumbar.",
        []),

    # ================= TRACCIÓN VERTICAL (10) =================
    _ex("Dominadas pronas", ["pull ups", "dominadas"],
        "espalda", ["biceps", "core"], "vertical_pull", ["barra_dominadas", "peso_corporal"], 2,
        "Desde brazos extendidos, lleva el pecho hacia la barra sin balanceo.",
        "Tracción vertical reina: el dorsal aduce y extiende el hombro contra el peso corporal.",
        ["hombro", "codo"]),
    _ex("Dominadas supinas", ["chin ups", "dominadas agarre supino"],
        "espalda", ["biceps", "core"], "vertical_pull", ["barra_dominadas", "peso_corporal"], 2,
        "Agarre al ancho de hombros con palmas hacia ti, sube hasta barbilla sobre barra.",
        "La supinación implica más al bíceps y suele permitir más repeticiones.",
        ["codo"]),
    _ex("Dominadas neutras", ["dominadas agarre neutro"],
        "espalda", ["biceps", "core"], "vertical_pull", ["barra_dominadas", "peso_corporal"], 2,
        "Palmas enfrentadas, codos hacia las costillas al subir.",
        "El agarre neutro es la posición más amable para hombro y codo.",
        []),
    _ex("Dominadas lastradas", ["weighted pull ups"],
        "espalda", ["biceps", "core"], "vertical_pull", ["barra_dominadas", "lastre"], 3,
        "Lastre estable en cinturón; mismas dominadas estrictas de siempre.",
        "Sobrecarga progresiva del patrón de tracción vertical más completo.",
        ["hombro", "codo"]),
    _ex("Jalón al pecho", ["lat pulldown", "polea al pecho", "jalón frontal"],
        "espalda", ["biceps"], "vertical_pull", ["polea", "maquina"], 1,
        "Ligera inclinación atrás fija, lleva la barra a la clavícula con codos abajo.",
        "Versión regulable de la dominada: misma aducción de hombro con carga ajustable.",
        []),
    _ex("Jalón agarre estrecho neutro", ["jalón neutro", "close grip pulldown"],
        "espalda", ["biceps"], "vertical_pull", ["polea", "maquina"], 1,
        "Maneral en V, tira hacia el pecho alto alargando el torso.",
        "El agarre estrecho neutro maximiza el recorrido del dorsal en el plano sagital.",
        []),
    _ex("Jalón unilateral en polea", ["jalón a una mano"],
        "espalda", ["biceps"], "vertical_pull", ["polea"], 2,
        "De rodillas o sentado, tira del codo hacia el bolsillo del mismo lado.",
        "La versión unilateral permite máximo estiramiento y corrige déficits laterales.",
        []),
    _ex("Jalón con brazos rectos en polea", ["straight arm pulldown", "pullover en polea de pie"],
        "espalda", ["triceps", "core"], "vertical_pull", ["polea"], 1,
        "Brazos casi rectos, lleva la barra de los hombros a las caderas en arco.",
        "Extensión pura de hombro: aísla el dorsal sin que el bíceps limite la serie.",
        []),
    _ex("Pullover en polea alta", ["cable pullover"],
        "espalda", ["pecho", "triceps"], "vertical_pull", ["polea"], 1,
        "Torso inclinado, arco amplio con codos semifijos hasta la cadera.",
        "Tensión constante en el dorsal a lo largo de todo el arco de extensión.",
        []),
    _ex("Pullover con mancuerna", ["dumbbell pullover"],
        "espalda", ["pecho", "triceps"], "vertical_pull", ["mancuernas", "banco"], 2,
        "Tumbado transversal al banco, baja la mancuerna tras la cabeza con codos semifijos.",
        "Gran estiramiento simultáneo de dorsal y pectoral bajo carga.",
        ["hombro"]),

    # ================= SENTADILLA (12) =================
    _ex("Sentadilla trasera con barra", ["back squat", "sentadilla con barra"],
        "cuadriceps", ["gluteos", "isquios", "core"], "squat", ["barra", "rack"], 2,
        "Barra sobre trapecios, baja entre las rodillas con torso firme y talones fijos.",
        "Patrón de rodilla dominante global: máxima transferencia de fuerza al tren inferior.",
        ["rodilla", "lumbar"]),
    _ex("Sentadilla frontal con barra", ["front squat"],
        "cuadriceps", ["gluteos", "core"], "squat", ["barra", "rack"], 3,
        "Barra en deltoides anteriores, codos altos, torso lo más vertical posible.",
        "La carga frontal verticaliza el torso: más cuádriceps y menos cizalla lumbar.",
        ["rodilla", "muneca"]),
    _ex("Sentadilla goblet", ["goblet squat", "sentadilla con mancuerna al pecho"],
        "cuadriceps", ["gluteos", "core"], "squat", ["mancuernas", "kettlebell"], 1,
        "Mancuerna pegada al pecho, baja entre las rodillas con codos por dentro.",
        "El contrapeso anterior enseña la mecánica de sentadilla profunda con torso erguido.",
        []),
    _ex("Sentadilla hack en máquina", ["hack squat"],
        "cuadriceps", ["gluteos"], "squat", ["maquina"], 1,
        "Pies a media plataforma, baja profundo sin despegar el sacro del respaldo.",
        "El respaldo fija el torso: flexión de rodilla profunda con mínima demanda lumbar.",
        ["rodilla"]),
    _ex("Prensa de piernas 45°", ["leg press", "prensa inclinada"],
        "cuadriceps", ["gluteos", "isquios"], "squat", ["maquina"], 1,
        "Baja controlado hasta donde la pelvis no bascule; no bloquees con golpe.",
        "Permite cargar el patrón de rodilla con el torso completamente descargado.",
        ["rodilla"]),
    _ex("Prensa de piernas horizontal", ["prensa sentada", "seated leg press"],
        "cuadriceps", ["gluteos"], "squat", ["maquina"], 1,
        "Espalda y sacro pegados al respaldo durante todo el recorrido.",
        "Versión más accesible de la prensa: ideal para principiantes y rehabilitación.",
        []),
    _ex("Sentadilla en multipower", ["sentadilla smith"],
        "cuadriceps", ["gluteos"], "squat", ["multipower"], 1,
        "Pies ligeramente adelantados respecto a la barra, baja vertical.",
        "La guía permite manipular el vector para sesgar cuádriceps o glúteo.",
        ["rodilla"]),
    _ex("Sentadilla a cajón", ["box squat", "sentadilla al banco"],
        "cuadriceps", ["gluteos", "isquios"], "squat", ["barra", "rack", "cajon"], 1,
        "Siéntate atrás con control hasta el cajón, pausa breve y sube sin balanceo.",
        "El cajón estandariza la profundidad y enseña a sentarse atrás con confianza.",
        []),
    _ex("Sentadilla Zercher", ["zercher squat"],
        "cuadriceps", ["gluteos", "core", "biceps"], "squat", ["barra", "rack"], 3,
        "Barra en el pliegue de los codos abrazada al cuerpo, torso erguido.",
        "La carga en los codos dispara la demanda de core y mantiene el torso vertical.",
        ["codo", "lumbar"]),
    _ex("Sentadilla sissy", ["sissy squat"],
        "cuadriceps", [], "knee_extension", ["peso_corporal", "maquina"], 3,
        "Rodillas adelante y torso atrás en línea con el muslo; rango progresivo.",
        "Flexión de rodilla extrema con cadera extendida: estiramiento máximo del recto femoral.",
        ["rodilla"]),
    _ex("Sentadilla pistol asistida", ["pistol squat asistida", "sentadilla a una pierna"],
        "cuadriceps", ["gluteos", "core"], "squat", ["peso_corporal", "bandas"], 3,
        "Sujétate de un soporte o banda, baja a una pierna con talón fijo.",
        "Fuerza unilateral con gran demanda de control de rodilla y tobillo.",
        ["rodilla"]),
    _ex("Sentadilla pausada con barra", ["pause squat"],
        "cuadriceps", ["gluteos", "core"], "squat", ["barra", "rack"], 2,
        "Pausa real de 2-3 s abajo manteniendo tensión, sube sin rebote.",
        "La pausa elimina el reflejo elástico: más tensión muscular con menos carga absoluta.",
        ["rodilla", "lumbar"]),

    # ================= BISAGRA DE CADERA (12) =================
    _ex("Peso muerto convencional", ["deadlift", "peso muerto"],
        "isquios", ["gluteos", "espalda", "trapecio", "antebrazos"], "hip_hinge", ["barra"], 2,
        "Barra pegada a la tibia, espalda neutra, empuja el suelo y estira la cadera.",
        "La bisagra cargada más global: cadena posterior completa más agarre y espalda.",
        ["lumbar"]),
    _ex("Peso muerto sumo", ["sumo deadlift"],
        "gluteos", ["isquios", "cuadriceps", "aductores"], "hip_hinge", ["barra"], 2,
        "Postura ancha con puntas abiertas, rodillas siguen a los pies, torso más vertical.",
        "La postura ancha acorta la palanca lumbar y recluta más aductor y glúteo.",
        ["cadera", "lumbar"]),
    _ex("Peso muerto rumano con barra", ["rdl", "peso muerto rumano"],
        "isquios", ["gluteos", "espalda"], "hip_hinge", ["barra"], 1,
        "Desde de pie, cadera atrás con rodillas semiflexionadas hasta media tibia.",
        "Bisagra con énfasis excéntrico: el isquio se alarga bajo carga, estímulo clave.",
        ["lumbar"]),
    _ex("Peso muerto rumano con mancuernas", ["rdl con mancuernas"],
        "isquios", ["gluteos"], "hip_hinge", ["mancuernas"], 1,
        "Mancuernas rozando los muslos, cadera atrás, espalda neutra siempre.",
        "Versión accesible del rumano: ideal para aprender la bisagra en casa o gym.",
        ["lumbar"]),
    _ex("Peso muerto con barra hexagonal", ["trap bar deadlift", "peso muerto hexagonal"],
        "cuadriceps", ["gluteos", "isquios", "trapecio"], "hip_hinge", ["barra_hexagonal"], 1,
        "Dentro de la barra, agarres neutros, empuja el suelo con torso firme.",
        "El centro de masa alineado reduce la cizalla lumbar: el tirón más amable de aprender.",
        []),
    _ex("Buenos días con barra", ["good morning"],
        "isquios", ["gluteos", "espalda"], "hip_hinge", ["barra", "rack"], 3,
        "Barra como en sentadilla, cadera atrás hasta torso ~45°, rodillas semiflexionadas.",
        "Bisagra con la carga lejos de la cadera: enorme palanca para isquios y erectores.",
        ["lumbar"]),
    _ex("Hiperextensiones 45°", ["back extension", "extensiones lumbares", "hiperextensiones"],
        "isquios", ["gluteos", "espalda"], "hip_hinge", ["maquina"], 1,
        "Pad en la cadera, baja redondeando lo justo y sube apretando glúteo.",
        "Extensión de cadera guiada; con pelvis retrovertida sesga el glúteo.",
        []),
    _ex("Hip thrust con barra", ["empuje de cadera", "hip thrust"],
        "gluteos", ["isquios", "cuadriceps"], "hip_extension", ["barra", "banco"], 1,
        "Espalda alta en el banco, barbilla al pecho, extiende y bloquea 1 s arriba.",
        "Tensión máxima del glúteo en acortamiento: el complemento perfecto de la bisagra.",
        []),
    _ex("Puente de glúteos", ["glute bridge", "puente de cadera en suelo"],
        "gluteos", ["isquios"], "hip_extension", ["peso_corporal", "barra"], 1,
        "Tumbado con rodillas flexionadas, eleva la cadera apretando glúteo arriba.",
        "Patrón base de extensión de cadera, progresable con carga sobre la pelvis.",
        []),
    _ex("Pull through en polea", ["cable pull through"],
        "gluteos", ["isquios"], "hip_hinge", ["polea"], 1,
        "De espaldas a la polea baja, cuerda entre las piernas, bisagra y extiende.",
        "La resistencia desde atrás enseña la extensión de cadera con tensión al final.",
        []),
    _ex("Swing con kettlebell", ["kettlebell swing", "balanceo ruso"],
        "gluteos", ["isquios", "core"], "hip_hinge", ["kettlebell"], 2,
        "Bisagra explosiva: la kettlebell flota hasta el pecho por el empuje de cadera.",
        "Potencia de cadera balística con gran demanda metabólica y de core.",
        ["lumbar"]),
    _ex("Peso muerto rumano a una pierna", ["single leg rdl", "peso muerto unilateral"],
        "isquios", ["gluteos", "core"], "hip_hinge", ["mancuernas", "kettlebell"], 2,
        "Cadera cuadrada al frente, la pierna libre extiende atrás como contrapeso.",
        "Bisagra unilateral: añade estabilidad de cadera y equilibrio al estímulo de isquio.",
        []),

    # ================= ZANCADA (8) =================
    _ex("Zancadas caminando con mancuernas", ["walking lunges", "zancadas"],
        "cuadriceps", ["gluteos", "core"], "lunge", ["mancuernas"], 2,
        "Pasos largos y estables, la rodilla trasera roza el suelo.",
        "Patrón unilateral dinámico: fuerza, estabilidad y gran coste metabólico.",
        ["rodilla"]),
    _ex("Zancada estática", ["split squat", "zancada en el sitio"],
        "cuadriceps", ["gluteos"], "lunge", ["mancuernas", "peso_corporal"], 1,
        "Posición de paso fija, sube y baja vertical sin cambiar los apoyos.",
        "La versión más estable de la zancada: ideal para aprender el patrón unilateral.",
        ["rodilla"]),
    _ex("Sentadilla búlgara", ["bulgarian split squat", "zancada búlgara"],
        "cuadriceps", ["gluteos"], "lunge", ["mancuernas", "banco"], 2,
        "Empeine trasero en el banco, baja vertical; el torso inclinado sesga el glúteo.",
        "El pie elevado concentra la carga en la pierna delantera: unilateral estrella.",
        ["rodilla"]),
    _ex("Zancada inversa", ["reverse lunge", "zancada atrás"],
        "cuadriceps", ["gluteos"], "lunge", ["mancuernas", "peso_corporal"], 1,
        "Paso atrás controlado, empuja con el talón delantero para volver.",
        "El paso atrás reduce el estrés de la rodilla delantera frente a la zancada frontal.",
        []),
    _ex("Zancada lateral", ["lateral lunge", "zancada al lado"],
        "cuadriceps", ["gluteos", "aductores"], "lunge", ["mancuernas", "peso_corporal"], 2,
        "Paso lateral amplio, siéntate sobre esa cadera con el otro pie plano.",
        "Trabajo en plano frontal: aductores y glúteo medio que la zancada normal no toca.",
        ["rodilla", "cadera"]),
    _ex("Subida a cajón", ["step up", "subida al banco"],
        "cuadriceps", ["gluteos"], "lunge", ["mancuernas", "cajon", "banco"], 1,
        "Sube empujando solo con la pierna del cajón, baja con control.",
        "Extensión unilateral de rodilla y cadera con transferencia directa a la vida diaria.",
        []),
    _ex("Split squat en multipower", ["zancada en smith"],
        "cuadriceps", ["gluteos"], "lunge", ["multipower"], 1,
        "Pie delantero adelantado a la barra, baja vertical por la guía.",
        "La guía elimina el equilibrio: permite acercarse al fallo en unilateral con seguridad.",
        ["rodilla"]),
    _ex("Zancada curtsy", ["curtsy lunge", "zancada cruzada"],
        "gluteos", ["cuadriceps", "aductores"], "lunge", ["mancuernas", "peso_corporal"], 2,
        "Cruza la pierna por detrás en diagonal manteniendo la cadera al frente.",
        "La aducción combinada con extensión enfatiza glúteo medio y mayor.",
        ["rodilla", "cadera"]),

    # ================= EXTENSIÓN / FLEXIÓN DE RODILLA (7) =================
    _ex("Extensión de rodilla en máquina", ["leg extension", "extensiones de cuádriceps"],
        "cuadriceps", [], "knee_extension", ["maquina"], 1,
        "Eje de la máquina alineado con la rodilla, extiende y aprieta 1 s.",
        "Único ejercicio que aísla el recto femoral en extensión: tensión pico en acortamiento.",
        ["rodilla"]),
    _ex("Extensión de rodilla unilateral", ["leg extension a una pierna"],
        "cuadriceps", [], "knee_extension", ["maquina"], 1,
        "Una pierna cada vez, mismo ajuste; controla la bajada 2-3 s.",
        "Corrige asimetrías de cuádriceps con el mismo aislamiento guiado.",
        ["rodilla"]),
    _ex("Curl femoral tumbado", ["leg curl tumbado", "curl de piernas"],
        "isquios", ["gemelos"], "knee_flexion", ["maquina"], 1,
        "Cadera pegada al banco, flexiona sin levantar la pelvis.",
        "Aísla la flexión de rodilla: complementa al rumano (que carga la cadera).",
        []),
    _ex("Curl femoral sentado", ["seated leg curl"],
        "isquios", [], "knee_flexion", ["maquina"], 1,
        "Muslos fijados por el pad, flexiona en rango completo.",
        "Con la cadera flexionada el isquio trabaja más alargado: mayor estímulo distal.",
        []),
    _ex("Curl femoral de pie unilateral", ["standing leg curl"],
        "isquios", [], "knee_flexion", ["maquina", "polea"], 1,
        "Talón al glúteo con la cadera quieta, baja con control.",
        "Flexión unilateral que evidencia y corrige diferencias entre piernas.",
        []),
    _ex("Curl nórdico", ["nordic curl", "curl nórdico de isquios"],
        "isquios", [], "knee_flexion", ["peso_corporal", "maquina"], 3,
        "Tobillos fijados, déjate caer recto frenando con los isquios.",
        "Excéntrico supramáximo del isquio: protector frente a lesiones de carrera.",
        ["rodilla"]),
    _ex("Curl femoral con deslizadores", ["slider leg curl", "curl con toalla"],
        "isquios", ["gluteos", "core"], "knee_flexion", ["deslizadores", "peso_corporal"], 2,
        "En puente de glúteo, desliza los talones lejos y vuelve sin caer la cadera.",
        "Flexión de rodilla con cadera extendida en cadena cerrada: opción sin máquina.",
        []),

    # ================= GLÚTEO ABD/ADD (7) =================
    _ex("Patada de glúteo en polea", ["glute kickback", "patada trasera en polea"],
        "gluteos", ["isquios"], "hip_extension", ["polea"], 1,
        "Tobillera en polea baja, extiende la cadera atrás sin arquear la lumbar.",
        "Extensión unilateral con tensión constante en el rango final del glúteo.",
        []),
    _ex("Hip thrust en máquina", ["hip thrust machine"],
        "gluteos", ["isquios"], "hip_extension", ["maquina"], 1,
        "Ajusta el pad sobre la pelvis, extiende y bloquea arriba 1 s.",
        "Misma curva del hip thrust con montaje en segundos: facilita la progresión.",
        []),
    _ex("Abducción de cadera en máquina", ["hip abduction", "máquina de abductores"],
        "gluteos", [], "hip_abduction", ["maquina"], 1,
        "Torso ligeramente inclinado adelante, abre con pausa fuera.",
        "Aísla el glúteo medio: estabilidad de pelvis y forma lateral de la cadera.",
        []),
    _ex("Abducción de cadera con banda", ["clamshell con banda", "abducción con banda"],
        "gluteos", [], "hip_abduction", ["bandas"], 1,
        "Banda sobre las rodillas, separa contra la resistencia sin rotar la pelvis.",
        "Activación accesible del glúteo medio: ideal en calentamientos y en casa.",
        []),
    _ex("Frog pump", ["puente de glúteo con plantas juntas"],
        "gluteos", [], "hip_extension", ["peso_corporal", "mancuernas"], 1,
        "Plantas de los pies juntas, rodillas abiertas, eleva la pelvis apretando.",
        "La rotación externa pre-acorta el glúteo: gran sensación con poca carga.",
        []),
    _ex("Aducción de cadera en máquina", ["máquina de aductores", "hip adduction"],
        "aductores", [], "hip_adduction", ["maquina"], 1,
        "Junta las piernas con control y abre lento hasta estiramiento cómodo.",
        "Aísla los aductores: estabilidad de cadera y prevención en deportes con cambios de dirección.",
        ["cadera"]),
    _ex("Plancha Copenhagen", ["copenhagen plank", "plancha de aductores"],
        "aductores", ["core"], "hip_adduction", ["banco", "peso_corporal"], 3,
        "Pie superior apoyado en el banco, cuerpo en línea; empieza con rodilla apoyada.",
        "Aductor en isometría de alta tensión: estándar preventivo en deportes de campo.",
        ["cadera"]),

    # ================= GEMELO / TIBIAL (5) =================
    _ex("Elevación de talones de pie", ["calf raise de pie", "gemelos de pie"],
        "gemelos", [], "plantar_flexion", ["maquina", "multipower", "mancuernas"], 1,
        "Estiramiento completo abajo 1 s, sube a máxima puntilla sin rebotar.",
        "Con rodilla extendida trabaja el gastrocnemio; la pausa abajo elimina el rebote del Aquiles.",
        ["tobillo"]),
    _ex("Elevación de talones sentado", ["calf raise sentado", "gemelos sentado"],
        "gemelos", [], "plantar_flexion", ["maquina"], 1,
        "Pad sobre las rodillas, mismo rango completo con pausa abajo.",
        "La rodilla flexionada desactiva el gastrocnemio y aísla el sóleo.",
        []),
    _ex("Elevación de talones en prensa", ["gemelos en prensa"],
        "gemelos", [], "plantar_flexion", ["maquina"], 1,
        "Punteras en el borde de la plataforma, rango completo controlado.",
        "Permite cargar la flexión plantar con la espalda totalmente apoyada.",
        []),
    _ex("Elevación de talones unilateral con mancuerna", ["gemelo a una pierna"],
        "gemelos", [], "plantar_flexion", ["mancuernas", "peso_corporal"], 1,
        "En un escalón, mancuerna del mismo lado, rango completo lento.",
        "El trabajo unilateral con déficit maximiza rango y corrige asimetrías.",
        ["tobillo"]),
    _ex("Elevación de talones tipo burro", ["donkey calf raise", "gemelo burro"],
        "gemelos", [], "plantar_flexion", ["maquina", "peso_corporal"], 2,
        "Torso flexionado a 90° con apoyo, carga sobre la pelvis, rango completo.",
        "La cadera flexionada pre-estira el gastrocnemio: mayor tensión en alargamiento.",
        ["lumbar"]),
    _ex("Elevación de puntas (tibial anterior)", ["tibialis raise", "flexión dorsal con banda"],
        "gemelos", [], "dorsiflexion", ["bandas", "peso_corporal"], 1,
        "Talones apoyados, sube las punteras hacia ti con pausa arriba.",
        "Fortalece el tibial anterior: equilibrio articular del tobillo y prevención en carrera.",
        []),

    # ================= FLEXIÓN DE CODO (9) =================
    _ex("Curl de bíceps con barra", ["barbell curl", "curl con barra recta"],
        "biceps", ["antebrazos"], "elbow_flexion", ["barra"], 1,
        "Codos pegados al torso, sube sin balanceo y baja en 2-3 s.",
        "Flexión con supinación fija: la barra recta permite la mayor carga del patrón.",
        ["muneca", "codo"]),
    _ex("Curl de bíceps con barra EZ", ["curl ez", "curl con barra z"],
        "biceps", ["antebrazos"], "elbow_flexion", ["barra_ez"], 1,
        "Agarre en las inclinaciones de la barra, codos fijos al costado.",
        "La semipronación de la EZ reduce el estrés de muñeca conservando el estímulo.",
        []),
    _ex("Curl alterno con mancuernas", ["curl alterno", "dumbbell curl"],
        "biceps", ["antebrazos"], "elbow_flexion", ["mancuernas"], 1,
        "Supina la muñeca mientras subes; alterna sin balancear el torso.",
        "La supinación activa durante la flexión es la doble función del bíceps.",
        []),
    _ex("Curl martillo", ["hammer curl", "curl neutro"],
        "biceps", ["antebrazos"], "elbow_flexion", ["mancuernas"], 1,
        "Palmas enfrentadas todo el recorrido, codos quietos.",
        "El agarre neutro carga braquial y braquiorradial: grosor total del brazo.",
        []),
    _ex("Curl inclinado con mancuernas", ["incline curl", "curl en banco inclinado"],
        "biceps", [], "elbow_flexion", ["mancuernas", "banco"], 2,
        "Respaldo a 45-60°, brazos colgando atrás, sube sin adelantar los codos.",
        "El hombro extendido alarga la cabeza larga: máxima tensión en estiramiento.",
        ["hombro"]),
    _ex("Curl predicador", ["preacher curl", "curl scott", "curl en banco scott"],
        "biceps", [], "elbow_flexion", ["barra_ez", "banco_scott", "maquina"], 1,
        "Axilas sobre el pad, extiende casi del todo abajo sin rebotar.",
        "El apoyo elimina el balanceo y castiga el rango de estiramiento del bíceps.",
        ["codo"]),
    _ex("Curl bayesian en polea", ["bayesian curl", "curl en polea tras el cuerpo"],
        "biceps", [], "elbow_flexion", ["polea"], 2,
        "De espaldas a la polea baja, brazo atrás, flexiona sin mover el codo.",
        "La polea desde atrás mantiene tensión máxima con el bíceps alargado.",
        []),
    _ex("Curl araña", ["spider curl"],
        "biceps", [], "elbow_flexion", ["mancuernas", "barra_ez", "banco"], 2,
        "Pecho apoyado en banco inclinado, brazos verticales colgando, sube estricto.",
        "Brazo perpendicular al suelo: tensión pico en el acortamiento completo.",
        []),
    _ex("Curl invertido con barra EZ", ["reverse curl", "curl agarre prono"],
        "antebrazos", ["biceps"], "elbow_flexion", ["barra_ez"], 1,
        "Agarre prono, muñecas firmes, sube sin que los nudillos caigan.",
        "El agarre prono prioriza braquiorradial y extensores: antebrazo y codo sanos.",
        ["muneca"]),

    # ================= EXTENSIÓN DE CODO (10) =================
    _ex("Press francés con barra EZ", ["skullcrusher", "rompecráneos", "extensión tumbado"],
        "triceps", [], "elbow_extension", ["barra_ez", "banco"], 2,
        "Baja la barra hacia la frente o detrás con codos estables, sin abrirlos.",
        "Extensión con hombro semiflexionado: carga la cabeza larga en alargamiento.",
        ["codo"]),
    _ex("Extensión de tríceps en polea con cuerda", ["pushdown con cuerda", "jalones de tríceps"],
        "triceps", [], "elbow_extension", ["polea"], 1,
        "Codos pegados, separa la cuerda abajo y bloquea 1 s.",
        "La cuerda permite extensión completa con pronación final: pico de contracción.",
        []),
    _ex("Extensión de tríceps en polea con barra", ["pushdown con barra"],
        "triceps", [], "elbow_extension", ["polea"], 1,
        "Barra recta o EZ, empuja hasta el bloqueo sin inclinarte sobre ella.",
        "La barra estandariza el gesto y admite más carga que la cuerda.",
        ["codo"]),
    _ex("Extensión de tríceps sobre la cabeza en polea", ["overhead cable extension"],
        "triceps", [], "elbow_extension", ["polea"], 2,
        "De espaldas a la polea, codos al cielo, extiende adelante-arriba.",
        "El hombro flexionado alarga la cabeza larga: el mejor estímulo de estiramiento.",
        ["hombro", "codo"]),
    _ex("Extensión de tríceps sobre la cabeza con mancuerna", ["extensión trasnuca", "french press de pie"],
        "triceps", [], "elbow_extension", ["mancuernas"], 1,
        "Mancuerna a dos manos tras la nuca, codos cerrados apuntando arriba.",
        "Versión libre del estiramiento de cabeza larga, viable en casa.",
        ["hombro", "codo"]),
    _ex("Patada de tríceps con mancuerna", ["kickback"],
        "triceps", [], "elbow_extension", ["mancuernas"], 1,
        "Torso inclinado, húmero paralelo al suelo fijo, extiende hasta bloquear.",
        "Tensión pico en el acortamiento total: complementa los gestos de estiramiento.",
        []),
    _ex("Fondos entre bancos", ["bench dips", "fondos de tríceps en banco"],
        "triceps", ["hombros", "pecho"], "elbow_extension", ["banco", "peso_corporal"], 1,
        "Manos al borde del banco, baja con el torso cerca de él.",
        "Cadena cerrada accesible; cuidado con bajar más allá del confort del hombro.",
        ["hombro"]),
    _ex("Press banca agarre cerrado", ["close grip bench press", "press cerrado"],
        "triceps", ["pecho", "hombros"], "elbow_extension", ["barra", "banco", "rack"], 2,
        "Agarre al ancho de hombros, codos cerca del torso, toca el pecho bajo.",
        "El press pesado del tríceps: el agarre estrecho desplaza la demanda del pectoral.",
        ["muneca", "hombro"]),
    _ex("JM press", ["jm press"],
        "triceps", ["pecho"], "elbow_extension", ["barra", "banco", "rack", "multipower"], 3,
        "Híbrido entre press cerrado y francés: baja la barra hacia la barbilla.",
        "Sobrecarga la extensión de codo con más estabilidad que el francés puro.",
        ["codo"]),
    _ex("Fondos en paralelas (énfasis tríceps)", ["dips tríceps"],
        "triceps", ["pecho", "hombros"], "elbow_extension", ["paralelas"], 2,
        "Torso vertical y codos cerrados; rango hasta codo a 90° aprox.",
        "La verticalidad concentra la extensión de codo con el peso corporal.",
        ["hombro"]),

    # ================= HOMBRO LATERAL / FRONTAL / ROTACIÓN (9) =================
    _ex("Elevaciones laterales con mancuernas", ["lateral raises", "vuelos laterales"],
        "hombros", [], "shoulder_abduction", ["mancuernas"], 1,
        "Sube hasta la horizontal con codos semiflexionados, baja en 2-3 s.",
        "Abducción pura: el deltoides medio es el responsable de la anchura de hombros.",
        ["hombro"]),
    _ex("Elevación lateral en polea unilateral", ["lateral raise en polea"],
        "hombros", [], "shoulder_abduction", ["polea"], 1,
        "Polea baja por detrás del cuerpo, sube en arco hasta la horizontal.",
        "La polea da tensión desde el primer grado, donde la mancuerna no pesa.",
        []),
    _ex("Elevaciones laterales en máquina", ["lateral raise machine"],
        "hombros", [], "shoulder_abduction", ["maquina"], 1,
        "Pads en los codos, abre hasta la horizontal sin encoger el cuello.",
        "Trayectoria guiada que permite llegar al fallo sin que la técnica se degrade.",
        []),
    _ex("Elevaciones laterales sentado", ["seated lateral raise"],
        "hombros", [], "shoulder_abduction", ["mancuernas", "banco"], 1,
        "Sentado para eliminar todo impulso, mismas pautas que de pie.",
        "Quitar el balanceo de cadera convierte cada kilo en estímulo real del deltoides.",
        ["hombro"]),
    _ex("Remo al mentón con barra EZ", ["upright row", "remo vertical"],
        "hombros", ["trapecio", "biceps"], "shoulder_abduction", ["barra_ez", "polea"], 2,
        "Agarre algo más ancho que los hombros, sube hasta el pecho, no más.",
        "Abducción con carga axial; el agarre ancho y rango medio protegen el manguito.",
        ["hombro"]),
    _ex("Elevación lateral con banda", ["lateral raise con banda"],
        "hombros", [], "shoulder_abduction", ["bandas"], 1,
        "Pisa la banda, sube hasta la horizontal con control.",
        "La resistencia creciente de la banda acentúa el final del recorrido.",
        []),
    _ex("Elevaciones frontales con mancuernas", ["front raises", "vuelos frontales"],
        "hombros", [], "shoulder_flexion", ["mancuernas", "disco"], 1,
        "Sube al frente hasta la horizontal, alternando o a la vez, sin balanceo.",
        "Flexión pura de hombro: accesorio del deltoides anterior cuando hay poco press.",
        ["hombro"]),
    _ex("Elevación frontal con disco", ["front raise con disco"],
        "hombros", [], "shoulder_flexion", ["disco"], 1,
        "Disco a dos manos, sube hasta los ojos y baja lento.",
        "El agarre a dos manos estabiliza el gesto y permite pausas arriba.",
        []),
    _ex("Rotación externa de hombro en polea", ["external rotation", "rotación externa con polea"],
        "hombros", [], "shoulder_external_rotation", ["polea", "bandas"], 1,
        "Codo pegado al costado a 90°, rota el antebrazo hacia fuera.",
        "Fortalece el manguito rotador: equilibrio articular y prevención en pressers.",
        []),

    # ================= TRAPECIO (3) =================
    _ex("Encogimientos con barra", ["shrugs con barra", "encogimientos de hombros"],
        "trapecio", ["antebrazos"], "scapular_elevation", ["barra"], 1,
        "Sube los hombros hacia las orejas con pausa de 1 s, sin rotar.",
        "Elevación escapular pura: el trapecio superior responde a cargas altas y pausas.",
        ["cuello"]),
    _ex("Encogimientos con mancuernas", ["shrugs con mancuernas"],
        "trapecio", ["antebrazos"], "scapular_elevation", ["mancuernas"], 1,
        "Mancuernas a los costados, mismo gesto con rango algo mayor.",
        "El agarre neutro lateral permite un recorrido más natural que la barra.",
        ["cuello"]),
    _ex("Encogimientos en multipower", ["shrugs en smith"],
        "trapecio", ["antebrazos"], "scapular_elevation", ["multipower"], 1,
        "Barra guiada por delante o detrás, pausa arriba en cada repetición.",
        "La guía elimina el equilibrio y deja toda la atención en la elevación escapular.",
        ["cuello"]),

    # ================= ANTEBRAZO (2) =================
    _ex("Curl de muñeca con barra", ["wrist curl", "flexión de muñeca"],
        "antebrazos", [], "elbow_flexion", ["barra", "mancuernas", "banco"], 1,
        "Antebrazos apoyados, deja rodar la barra a los dedos y flexiona.",
        "Flexores del antebrazo: agarre más fuerte para tirones y pesos muertos.",
        ["muneca"]),
    _ex("Extensión de muñeca con barra", ["reverse wrist curl", "extensión de muñeca"],
        "antebrazos", [], "elbow_extension", ["barra", "mancuernas", "banco"], 1,
        "Palmas hacia abajo apoyadas, extiende las muñecas con poco peso.",
        "Extensores del antebrazo: equilibran a los flexores y protegen el codo.",
        ["muneca", "codo"]),

    # ================= CORE ANTI-EXTENSIÓN (6) =================
    _ex("Plancha abdominal", ["plank", "plancha frontal"],
        "core", ["hombros"], "core_anti_extension", ["peso_corporal"], 1,
        "Antebrazos bajo los hombros, pelvis neutra, glúteo y abdomen firmes.",
        "Isometría anti-extensión: el core resiste que la gravedad arquee la lumbar.",
        []),
    _ex("Plancha con lastre", ["weighted plank"],
        "core", ["hombros"], "core_anti_extension", ["peso_corporal", "disco", "lastre"], 2,
        "Disco centrado en la espalda baja-media, misma postura impecable.",
        "Progresión de intensidad de la plancha sin alargar series eternas.",
        ["lumbar"]),
    _ex("Rueda abdominal", ["ab wheel", "rodillo abdominal"],
        "core", ["hombros", "espalda"], "core_anti_extension", ["maquina", "peso_corporal"], 3,
        "Desde rodillas, rueda adelante solo hasta donde la lumbar no se arquee.",
        "Anti-extensión dinámica de alta demanda: el rango es la variable de progresión.",
        ["lumbar", "hombro"]),
    _ex("Dead bug", ["bicho muerto"],
        "core", [], "core_anti_extension", ["peso_corporal"], 1,
        "Lumbar pegada al suelo, extiende brazo y pierna contrarios lento.",
        "Enseña a disociar extremidades con pelvis estable: base de control lumbopélvico.",
        []),
    _ex("Body saw", ["sierra en plancha"],
        "core", ["hombros"], "core_anti_extension", ["deslizadores", "peso_corporal"], 2,
        "En plancha de antebrazos, desliza el cuerpo atrás y adelante pocos cm.",
        "El desplazamiento alarga la palanca: intensifica la plancha sin añadir carga.",
        ["hombro"]),
    _ex("Plancha con brazos extendidos", ["long lever plank", "plancha extendida"],
        "core", ["hombros"], "core_anti_extension", ["peso_corporal"], 2,
        "Manos más adelantadas que los hombros, cuerpo en línea férrea.",
        "Adelantar los apoyos multiplica el torque anti-extensión sobre el abdomen.",
        ["hombro", "muneca"]),

    # ================= CORE ANTI-ROTACIÓN (5) =================
    _ex("Press Pallof", ["pallof press", "antirrotación en polea"],
        "core", [], "core_anti_rotation", ["polea", "bandas"], 1,
        "Perpendicular a la polea, extiende los brazos al frente sin girar el torso.",
        "Anti-rotación pura: los oblicuos resisten el giro en lugar de producirlo.",
        []),
    _ex("Plancha lateral", ["side plank"],
        "core", ["hombros", "gluteos"], "core_anti_rotation", ["peso_corporal"], 1,
        "Codo bajo el hombro, cadera alta en línea, sin hundirte.",
        "Isometría anti-flexión lateral: oblicuos y glúteo medio en cadena.",
        ["hombro"]),
    _ex("Bird dog", ["perro de caza", "cuadrupedia alterna"],
        "core", ["gluteos", "espalda"], "core_anti_rotation", ["peso_corporal"], 1,
        "En cuadrupedia, extiende brazo y pierna contrarios sin bascular la pelvis.",
        "Estabilidad rotacional con extensión de cadera: control lumbopélvico básico.",
        []),
    _ex("Leñador en polea", ["cable chop", "woodchopper"],
        "core", ["hombros"], "core_anti_rotation", ["polea"], 2,
        "De arriba a abajo en diagonal con brazos casi rectos, pivota desde la cadera.",
        "El torso transmite el giro de la cadera: patrón rotacional con control.",
        ["lumbar"]),
    _ex("Paseo del granjero unilateral", ["suitcase carry", "paseo de la maleta"],
        "core", ["antebrazos", "trapecio"], "core_anti_rotation", ["mancuernas", "kettlebell"], 1,
        "Carga pesada en una mano, camina erguido sin inclinarte hacia ella.",
        "Anti-flexión lateral dinámica más agarre: core funcional con transferencia real.",
        []),

    # ================= CORE FLEXIÓN (6) =================
    _ex("Crunch en polea alta", ["cable crunch", "crunch de rodillas en polea"],
        "core", [], "core_flexion", ["polea"], 1,
        "De rodillas, cuerda junto a la cabeza, flexiona el torso llevando codos a muslos.",
        "Flexión de columna con carga regulable: el recto abdominal como motor principal.",
        ["lumbar"]),
    _ex("Crunch en máquina", ["machine crunch", "abdominal en máquina"],
        "core", [], "core_flexion", ["maquina"], 1,
        "Flexiona acercando costillas a pelvis y vuelve con control.",
        "Resistencia guiada y progresiva para hipertrofiar el recto abdominal.",
        []),
    _ex("Elevaciones de piernas colgado", ["hanging leg raise", "elevación de piernas en barra"],
        "core", ["antebrazos"], "core_flexion", ["barra_dominadas"], 3,
        "Colgado, sube las piernas rectas curvando la pelvis al final, sin balanceo.",
        "La retroversión final de la pelvis es lo que activa de verdad el abdomen bajo.",
        ["hombro"]),
    _ex("Elevaciones de rodillas colgado", ["hanging knee raise"],
        "core", ["antebrazos"], "core_flexion", ["barra_dominadas"], 1,
        "Rodillas al pecho enrollando la pelvis, baja sin balanceo.",
        "Versión accesible de la elevación colgado con la misma clave pélvica.",
        []),
    _ex("Crunch en banco declinado", ["decline crunch", "abdominales en banco declinado"],
        "core", [], "core_flexion", ["banco", "disco"], 1,
        "Baja solo hasta medio recorrido y sube enrollando vértebra a vértebra.",
        "El declive aumenta el rango bajo carga; lastrable con disco al pecho.",
        ["lumbar", "cuello"]),
    _ex("Crunch bicicleta", ["bicycle crunch"],
        "core", [], "core_flexion", ["peso_corporal"], 1,
        "Codo hacia rodilla contraria alternando, lento y sin tirar del cuello.",
        "Combina flexión y rotación: recto abdominal y oblicuos en un gesto.",
        ["cuello"]),
]
