# -*- coding: utf-8 -*-
"""Ejercicios de CASA/EXTERIOR (peso corporal y bandas) — refuerzo de cobertura.

La auditoría con perfiles sintéticos demostró que un cliente que entrena en casa
sin material (o solo con bandas) se quedaba con 5-11 ejercicios tras el filtro
determinista: imposible montar un plan completo. Este seed añade la cobertura
mínima por grupo muscular SIN equipamiento de gimnasio.

Mismas convenciones que `exercises_data.py` (músculos/patrones/equipo/contra).
Se insertan POR NOMBRE en cada arranque (como la maquinaria): producción los
recibe en el siguiente deploy sin tocar filas existentes.
"""

from app.seeds.exercises_data import _ex

HOME_EXERCISES = [
    # ---------------- PIERNA (empuje de rodilla / zancada / squat) ----------
    _ex("Sentadilla búlgara con peso corporal", ["bulgarian split squat", "sentadilla dividida"],
        "cuadriceps", ["gluteos", "isquios"], "lunge", ["peso_corporal"], 2,
        "Pie trasero elevado en silla o sofá; torso ligeramente inclinado; baja controlado.",
        "Dominante de rodilla unilateral: gran estímulo sin carga externa.",
        ["rodilla"]),
    _ex("Zancadas caminando sin carga", ["walking lunge", "zancada alterna"],
        "cuadriceps", ["gluteos"], "lunge", ["peso_corporal"], 1,
        "Paso largo, rodilla trasera cerca del suelo, torso erguido.",
        "Patrón de zancada básico; progresable con mochila.",
        ["rodilla"]),
    _ex("Sentadilla en pared (isométrica)", ["wall sit", "silla en la pared"],
        "cuadriceps", ["gluteos"], "squat", ["peso_corporal"], 1,
        "Espalda apoyada en la pared, rodillas a 90°; mantén el tiempo objetivo.",
        "Isométrico tolerable para rodillas irritables: tensión sin impacto.",
        []),
    _ex("Sentadilla a una pierna al cajón asistida", ["pistol al cajón", "single leg squat asistida"],
        "cuadriceps", ["gluteos", "core"], "squat", ["peso_corporal"], 2,
        "Baja a un asiento alto con una pierna, ayúdate del marco de una puerta si hace falta.",
        "Fuerza unilateral avanzada sin material.",
        ["rodilla"]),
    # ---------------- CADERA / GLÚTEO / ISQUIOS ------------------------------
    _ex("Puente de glúteo", ["glute bridge", "elevación de cadera"],
        "gluteos", ["isquios", "core"], "hip_extension", ["peso_corporal"], 1,
        "Tumbado, pies cerca del glúteo; sube la cadera apretando el glúteo arriba.",
        "Extensión de cadera segura para lumbares sensibles.",
        []),
    _ex("Puente de glúteo a una pierna", ["single leg glute bridge", "hip thrust unilateral suelo"],
        "gluteos", ["isquios"], "hip_extension", ["peso_corporal"], 2,
        "Como el puente, con una pierna extendida; cadera nivelada.",
        "Unilateral: duplica el estímulo por pierna sin carga.",
        []),
    _ex("Peso muerto rumano a una pierna sin carga", ["single leg RDL", "peso muerto unilateral"],
        "isquios", ["gluteos", "core"], "hip_hinge", ["peso_corporal"], 2,
        "Bisagra de cadera sobre una pierna, espalda neutra; llega hasta donde controles.",
        "Patrón de bisagra + equilibrio; progresable con cualquier peso casero.",
        ["lumbar"]),
    _ex("Curl femoral con toalla deslizante", ["curl nórdico asistido en suelo", "leg curl deslizante"],
        "isquios", ["gluteos"], "knee_flexion", ["peso_corporal"], 2,
        "Tumbado boca arriba con talones sobre toalla en suelo liso: puente y desliza.",
        "Flexión de rodilla activa sin máquina.",
        ["rodilla"]),
    _ex("Elevación de gemelo a una pierna en escalón", ["calf raise unilateral", "gemelo al fallo en escalón"],
        "gemelos", [], "plantar_flexion", ["peso_corporal"], 1,
        "Metatarso en el borde del escalón; recorrido completo, pausa arriba.",
        "Carga suficiente al fallo con el propio peso.",
        ["tobillo"]),
    # ---------------- ESPALDA / TRACCIÓN ------------------------------------
    _ex("Remo invertido bajo una mesa", ["inverted row casero", "remo australiano en mesa"],
        "espalda", ["biceps", "trapecio"], "horizontal_pull", ["peso_corporal"], 1,
        "Bajo una mesa robusta, cuerpo recto; tira del pecho hacia el borde.",
        "Única tracción horizontal sin material: imprescindible en casa.",
        []),
    _ex("Remo con banda sentado", ["remo elástico", "band row"],
        "espalda", ["biceps"], "horizontal_pull", ["bandas"], 1,
        "Banda en los pies, torso firme; lleva codos atrás sin encoger hombros.",
        "Tracción horizontal con resistencia progresiva de banda.",
        []),
    _ex("Jalón con banda de pie", ["lat pulldown con banda", "jalón elástico"],
        "espalda", ["biceps"], "vertical_pull", ["bandas"], 1,
        "Banda anclada arriba (puerta); tira de codos hacia el bolsillo.",
        "Tracción vertical sin barra de dominadas.",
        ["hombro"]),
    _ex("Band pull-apart", ["apertura de banda", "pull apart"],
        "trapecio", ["hombros", "espalda"], "horizontal_pull", ["bandas"], 1,
        "Brazos al frente, separa la banda hasta el pecho apretando escápulas.",
        "Salud escapular y volumen de espalda alta con material mínimo.",
        []),
    # ---------------- EMPUJE / HOMBRO / BRAZO --------------------------------
    _ex("Press de pecho con banda", ["press elástico", "band chest press"],
        "pecho", ["triceps", "hombros"], "horizontal_push", ["bandas"], 1,
        "Banda por la espalda; empuja al frente sin perder la escápula.",
        "Empuje horizontal sin apoyar muñecas en el suelo (alternativa a flexiones).",
        []),
    _ex("Press de hombro con banda", ["overhead press con banda", "press militar elástico"],
        "hombros", ["triceps"], "vertical_push", ["bandas"], 1,
        "De pie sobre la banda; empuja vertical con core firme.",
        "Empuje vertical de casa con resistencia regulable.",
        ["hombro"]),
    _ex("Elevaciones laterales con banda", ["lateral raise banda"],
        "hombros", [], "shoulder_abduction", ["bandas"], 1,
        "Pisa la banda; sube hasta la horizontal con codo blando.",
        "Deltoides medio sin mancuernas.",
        []),
    _ex("Face pull con banda", ["face pull elástico"],
        "hombros", ["trapecio", "espalda"], "shoulder_external_rotation", ["bandas"], 1,
        "Banda anclada a la altura de la cara; tira separando las manos.",
        "Rotación externa + escápula: salud de hombro en casa.",
        []),
    _ex("Curl de bíceps con banda", ["biceps curl banda"],
        "biceps", ["antebrazos"], "elbow_flexion", ["bandas"], 1,
        "Pisa la banda, codos pegados; sube controlando la bajada.",
        "Flexión de codo con tensión creciente al acortar.",
        ["codo"]),
    _ex("Extensión de tríceps con banda sobre cabeza", ["overhead triceps banda"],
        "triceps", [], "elbow_extension", ["bandas"], 1,
        "Banda anclada abajo/atrás; extiende sobre la cabeza sin abrir codos.",
        "Cabeza larga del tríceps sin polea.",
        ["codo", "hombro"]),
    # ---------------- CORE / CARDIO ------------------------------------------
    _ex("Marcha del oso", ["bear crawl", "cuadrupedia dinámica"],
        "core", ["hombros", "cuadriceps"], "core_anti_extension", ["peso_corporal"], 1,
        "A cuatro apoyos con rodillas a 2 cm del suelo; avanza corto y estable.",
        "Anti-extensión dinámica y coordinación, sin material.",
        ["muneca"]),
    _ex("Escaladores", ["mountain climbers"],
        "core", ["hombros", "cuadriceps"], "core_anti_extension", ["peso_corporal"], 1,
        "En plancha alta, lleva rodillas al pecho alternando con cadera estable.",
        "Core + demanda cardiovascular en el mismo gesto.",
        ["muneca"]),
    _ex("Sentadilla con salto", ["jump squat", "sentadilla pliométrica"],
        "cuadriceps", ["gluteos", "gemelos"], "squat", ["peso_corporal"], 2,
        "Sentadilla y salto vertical; amortigua la caída con la cadera atrás.",
        "Potencia/cardio de tren inferior sin material (alto impacto).",
        ["rodilla", "tobillo"]),
]
