# -*- coding: utf-8 -*-
"""Maquinaria del gimnasio del coach (seed idempotente por fila).

Listado real de máquinas de la sala (Panatta, Nautilus, Etenon, Maxpump,
Glute Builder/Prime, Platinum, Tuff Stuff, máquinas sin marca, zona de cardio
y trineos). La MARCA va en el nombre canónico — "Hip Thrust (Panatta)" — para
distinguir unidades equivalentes de marcas distintas; el nombre a secas queda
como alias para que el buscador del editor las encuentre igual.

Convenciones idénticas a exercises_data.py, con una extensión declarada:
- muscle_primary "cardio" y movement_pattern "cardio" para la zona de cardio
  (aparecen como grupo propio en el buscador del editor).
- equipment "trineo" para los trineos de arrastre/empuje.

A diferencia de la biblioteca base (que solo se siembra con la tabla vacía),
estas filas se insertan POR NOMBRE si faltan: una instalación en producción
las recibe en el siguiente deploy sin tocar las existentes.
"""

from app.seeds.exercises_data import _ex

MACHINE_EXERCISES = [
    # ============================ PANATTA ============================
    _ex("Press vertical a discos (Panatta)", ["Press vertical a discos"],
        "pecho", ["triceps", "hombros"], "horizontal_push", ["maquina", "disco"], 1,
        "Espalda apoyada, escápulas retraídas; empuja sin bloquear los codos.",
        "Press de pecho guiado con carga a discos: tensión estable sin estabilizadores.",
        []),
    _ex("Aperturas superiores (Panatta)", ["Aperturas superiores"],
        "pecho", ["hombros"], "horizontal_push", ["maquina"], 1,
        "Codos ligeramente flexionados fijos; junta los brazos en arco controlado.",
        "Aducción horizontal pura: aísla el pectoral (haz clavicular) sin tríceps.",
        []),
    _ex("Press dual en Smith superior (Panatta)", ["Press dual en Smith superior"],
        "pecho", ["hombros", "triceps"], "horizontal_push", ["multipower", "banco"], 1,
        "Banco inclinado bajo la barra guiada; baja al pecho alto y empuja recto.",
        "Trayectoria fija: permite acercarse al fallo con seguridad en press inclinado.",
        ["hombro"]),
    _ex("Press dual plano (Panatta)", ["Press dual plano"],
        "pecho", ["triceps"], "horizontal_push", ["maquina"], 1,
        "Agarre a la altura del pecho medio; empuja y controla la vuelta 2-3 s.",
        "Press convergente plano: recorrido natural del pectoral esternal.",
        []),
    _ex("Elevaciones laterales (Panatta)", ["Elevaciones laterales en máquina Panatta"],
        "hombros", [], "shoulder_abduction", ["maquina"], 1,
        "Brazos contra las almohadillas; sube hasta la horizontal sin encoger hombros.",
        "Abducción guiada: tensión constante en el deltoides medio en todo el arco.",
        []),
    _ex("Remo a discos con apoyo en T (Panatta)", ["Remo a discos con apoyo en T", "Remo T Panatta"],
        "espalda", ["biceps", "trapecio"], "horizontal_pull", ["maquina", "disco"], 1,
        "Pecho apoyado en el pad; tira llevando los codos atrás y junta escápulas.",
        "El apoyo esternal elimina el impulso lumbar: toda la carga va al dorsal.",
        []),
    _ex("Jalón al pecho (Panatta)", ["Jalón al pecho Panatta"],
        "espalda", ["biceps"], "vertical_pull", ["maquina"], 1,
        "Torso erguido con leve inclinación; lleva la barra a la clavícula.",
        "Tracción vertical guiada: dorsal ancho con asistencia estable de la máquina.",
        []),
    _ex("Prensa vertical (Panatta)", ["Prensa vertical"],
        "cuadriceps", ["gluteos"], "squat", ["maquina", "disco"], 1,
        "Pies al ancho de caderas en la plataforma; baja controlado sin despegar el lumbar.",
        "Empuje vertical con espalda fija: gran estímulo de cuádriceps sin carga axial.",
        ["rodilla"]),
    _ex("Hip Thrust (Panatta)", ["Hip Thrust Panatta"],
        "gluteos", ["isquios"], "hip_extension", ["maquina"], 1,
        "Espalda alta en el respaldo; extiende cadera hasta bloquear y aprieta arriba 1 s.",
        "Extensión de cadera con pico de tensión arriba: el mejor constructor de glúteo.",
        []),
    _ex("Abducciones (Panatta)", ["Abducciones Panatta", "Máquina de abducciones Panatta"],
        "gluteos", [], "hip_abduction", ["maquina"], 1,
        "Abre contra las almohadillas sin balancear el torso; controla la vuelta.",
        "Abducción sentada: glúteo medio, clave de estabilidad de cadera.",
        []),
    _ex("Patada de glúteo vertical (Panatta)", ["Patada de glúteo vertical"],
        "gluteos", ["isquios"], "hip_extension", ["maquina"], 1,
        "Rodilla en el pad, empuja la plataforma hacia arriba con el talón.",
        "Extensión de cadera unilateral vertical: glúteo mayor con cuádriceps mínimo.",
        []),
    _ex("Patada de glúteo horizontal (Panatta)", ["Patada de glúteo horizontal"],
        "gluteos", ["isquios"], "hip_extension", ["maquina"], 1,
        "Empuja hacia atrás con el talón hasta extender la cadera; no arquees el lumbar.",
        "Extensión de cadera horizontal guiada, tensión continua en glúteo.",
        []),
    _ex("Hiperextensión inversa (Panatta)", ["Hiperextensión inversa"],
        "gluteos", ["isquios", "espalda"], "hip_extension", ["maquina"], 2,
        "Torso fijo en el banco; sube las piernas con glúteo, sin latigazo lumbar.",
        "Extensión de cadera con columna neutra: glúteo/femoral descargando el lumbar.",
        ["lumbar"]),
    _ex("Tríceps tras nuca (Panatta)", ["Tríceps tras nuca en máquina"],
        "triceps", [], "elbow_extension", ["maquina"], 1,
        "Codos fijos junto a la cabeza; extiende sin abrir los codos.",
        "Extensión de codo con hombro flexionado: énfasis en la cabeza larga.",
        ["codo"]),
    _ex("Dual tríceps/bíceps (Panatta)", ["Dual tríceps/bíceps", "Máquina dual de brazos Panatta"],
        "triceps", ["biceps"], "elbow_extension", ["maquina"], 1,
        "Configura el modo (extensión o curl); codos alineados con el eje de giro.",
        "Estación dual de brazo: extensión y flexión de codo guiadas en una máquina.",
        []),
    _ex("Banco de curl predicador (Panatta)", ["Banco de curl predicador", "Curl predicador Panatta"],
        "biceps", ["antebrazos"], "elbow_flexion", ["banco_scott", "barra_ez"], 1,
        "Axilas encajadas en el pad; extiende casi del todo abajo sin rebotar.",
        "El apoyo elimina el balanceo: bíceps aislado con estiramiento cargado.",
        ["codo"]),
    _ex("Contractora pec deck (Panatta)", ["Contractora (pec deck)", "Pec deck Panatta"],
        "pecho", [], "horizontal_push", ["maquina"], 1,
        "Codos a la altura del pecho; junta y aprieta 1 s en el centro.",
        "Aducción horizontal aislada con tensión máxima en acortamiento.",
        []),
    _ex("Rotación de cadera (Panatta)", ["Rotación de cadera"],
        "gluteos", ["aductores"], "hip_abduction", ["maquina"], 1,
        "Pivota la pierna contra la resistencia con la pelvis estable.",
        "Rotadores y glúteo medio: útil para salud de cadera y control pélvico.",
        ["cadera"]),

    # ============================ NAUTILUS ============================
    _ex("Press superior (Nautilus)", ["Press superior Nautilus"],
        "pecho", ["hombros", "triceps"], "horizontal_push", ["maquina"], 1,
        "Empuje inclinado guiado; no despegues la espalda del respaldo.",
        "Press convergente superior: pectoral clavicular con hombro protegido.",
        []),
    _ex("Press plano (Nautilus)", ["Press plano Nautilus"],
        "pecho", ["triceps"], "horizontal_push", ["maquina"], 1,
        "Agarre al pecho medio; empuja y controla la excéntrica.",
        "Press de pecho guiado con leva Nautilus: resistencia acomodada al recorrido.",
        []),
    _ex("Press militar (Nautilus)", ["Press militar Nautilus"],
        "hombros", ["triceps"], "vertical_push", ["maquina"], 1,
        "Core firme; empuja vertical sin arquear el lumbar.",
        "Press de hombro sentado guiado: deltoides anterior/medio sin estabilización.",
        ["hombro"]),
    _ex("Pec Deck (Nautilus)", ["Pec deck Nautilus"],
        "pecho", [], "horizontal_push", ["maquina"], 1,
        "Codos a la altura del pecho; junta en arco y aprieta en el centro.",
        "Aislamiento del pectoral con tensión pico en aducción completa.",
        []),
    _ex("Elevaciones laterales a placas (Nautilus)", ["Elevaciones laterales a placas"],
        "hombros", [], "shoulder_abduction", ["maquina"], 1,
        "Sube los brazos hasta la horizontal; baja 2-3 s.",
        "Abducción con placas: curva de resistencia estable para el deltoides medio.",
        []),
    _ex("Remo (Nautilus)", ["Remo Nautilus"],
        "espalda", ["biceps"], "horizontal_pull", ["maquina"], 1,
        "Pecho en el apoyo; tira con los codos pegados y junta escápulas.",
        "Remo guiado con pecho apoyado: dorsal y romboides sin fatiga lumbar.",
        []),
    _ex("Jalón a discos (Nautilus)", ["Jalón a discos Nautilus"],
        "espalda", ["biceps"], "vertical_pull", ["maquina", "disco"], 1,
        "Tira hacia la clavícula llevando los codos al costado.",
        "Tracción vertical a discos: carga lineal y arranque estable.",
        []),
    _ex("Jalón diagonal (Nautilus)", ["Jalón diagonal"],
        "espalda", ["biceps"], "vertical_pull", ["maquina"], 1,
        "Tira en diagonal hacia el pecho bajo; siente el dorsal estirar arriba.",
        "Ángulo diagonal: dorsal en su línea de fibras con gran rango.",
        []),
    _ex("Dominadas asistidas (Nautilus)", ["Dominadas asistidas", "Máquina de dominadas asistidas"],
        "espalda", ["biceps"], "vertical_pull", ["maquina", "peso_corporal"], 1,
        "Rodillas en la plataforma; sube el pecho a la barra y baja controlado.",
        "Dominada con contrapeso: patrón completo accesible a cualquier nivel.",
        []),
    _ex("Polea dual unible (Nautilus)", ["Polea dual unible", "Doble polea Nautilus"],
        "espalda", ["hombros", "biceps"], "horizontal_pull", ["polea"], 1,
        "Ajusta la altura de las poleas al ejercicio; controla la vuelta siempre.",
        "Estación de poleas ajustables: cruces, remos, jalones y trabajo unilateral.",
        []),
    _ex("Femoral tumbado (Nautilus)", ["Femoral tumbado Nautilus"],
        "isquios", [], "knee_flexion", ["maquina"], 1,
        "Cadera pegada al banco; flexiona hasta el glúteo y baja 3 s.",
        "Flexión de rodilla tumbado: isquios con la cadera extendida.",
        ["rodilla"]),
    _ex("Femoral sentado (Nautilus)", ["Femoral sentado Nautilus"],
        "isquios", [], "knee_flexion", ["maquina"], 1,
        "Muslos fijados por el pad; flexiona al máximo y controla la vuelta.",
        "Con cadera flexionada el isquio trabaja más estirado: mayor estímulo.",
        ["rodilla"]),
    _ex("Gemelo en prensa (Nautilus)", ["Gemelo en prensa"],
        "gemelos", [], "plantar_flexion", ["maquina"], 1,
        "Punteras en el borde; estira abajo 1 s y sube al máximo.",
        "Flexión plantar con pierna extendida: gastrocnemio con carga alta y segura.",
        []),
    _ex("Abdominales (Nautilus)", ["Máquina de abdominales Nautilus"],
        "core", [], "core_flexion", ["maquina"], 1,
        "Encorva el tronco acercando costillas a pelvis; no tires con los brazos.",
        "Flexión de tronco con carga regulable: recto abdominal progresable.",
        []),

    # ============================ ETENON ============================
    _ex("Press vertical (Etenon)", ["Press vertical Etenon"],
        "pecho", ["triceps"], "horizontal_push", ["maquina"], 1,
        "Empuja sin bloquear codos; vuelta controlada al pecho.",
        "Press de pecho guiado vertical: patrón seguro para cargar fuerte.",
        []),
    _ex("Press de palanca (Etenon)", ["Press de palanca Etenon"],
        "pecho", ["triceps"], "horizontal_push", ["maquina", "disco"], 1,
        "Ajusta el asiento para que el agarre quede al pecho medio.",
        "Palanca a discos: curva de fuerza natural y carga por lados independiente.",
        []),
    _ex("Press superior a discos (Etenon)", ["Press superior a discos"],
        "pecho", ["hombros", "triceps"], "horizontal_push", ["maquina", "disco"], 1,
        "Empuje inclinado; codos a unos 45º del torso.",
        "Inclinado a discos: clavicular del pectoral con arranque estable.",
        []),
    _ex("Press militar (Etenon)", ["Press militar Etenon"],
        "hombros", ["triceps"], "vertical_push", ["maquina"], 1,
        "Empuja vertical con el core firme; baja a la altura de las orejas.",
        "Press de hombro guiado: deltoides con lumbar protegido.",
        ["hombro"]),
    _ex("Jalón al pecho a discos (Etenon)", ["Jalón al pecho a discos"],
        "espalda", ["biceps"], "vertical_pull", ["maquina", "disco"], 1,
        "Tira a la clavícula con el pecho alto.",
        "Tracción vertical a discos: dorsal con resistencia lineal.",
        []),
    _ex("Remo con apoyo a placas (Etenon)", ["Remo con apoyo a placas"],
        "espalda", ["biceps"], "horizontal_pull", ["maquina"], 1,
        "Pecho en el pad; lleva los codos atrás sin encoger el cuello.",
        "Remo apoyado a placas: espalda media sin impulso lumbar.",
        []),
    _ex("Remo de palanca a discos (Etenon)", ["Remo de palanca a discos"],
        "espalda", ["biceps", "trapecio"], "horizontal_pull", ["maquina", "disco"], 1,
        "Remada unilateral o bilateral; junta escápulas al final.",
        "Palanca a discos: permite remar pesado con torso fijado.",
        []),
    _ex("Remo en Smith a discos (Etenon)", ["Remo en Smith a discos"],
        "espalda", ["biceps"], "horizontal_pull", ["multipower", "disco"], 2,
        "Bisagra de cadera estable; tira de la barra guiada al abdomen.",
        "Remo con barra guiada: trayectoria fija que simplifica la técnica.",
        ["lumbar"]),
    _ex("Hack Squat (Etenon)", ["Hack squat Etenon"],
        "cuadriceps", ["gluteos"], "squat", ["maquina", "disco"], 1,
        "Pies centrados; baja profundo sin despegar el lumbar del respaldo.",
        "Sentadilla guiada con respaldo: cuádriceps dominante sin carga axial libre.",
        ["rodilla"]),
    _ex("Gemelo sentado (Etenon)", ["Gemelo sentado Etenon"],
        "gemelos", [], "plantar_flexion", ["maquina"], 1,
        "Rodillas bajo el pad; estira bien abajo y sube al máximo.",
        "Con rodilla flexionada trabaja el sóleo: clave para el volumen del gemelo.",
        []),
    _ex("Prensa de palanca unilateral (Etenon)", ["Prensa de palanca unilateral"],
        "cuadriceps", ["gluteos"], "squat", ["maquina", "disco"], 1,
        "Una pierna cada vez; baja controlado y empuja con todo el pie.",
        "Prensa unilateral: corrige asimetrías y limita la carga lumbar.",
        ["rodilla"]),
    _ex("Curl bíceps a discos (Etenon)", ["Curl bíceps a discos"],
        "biceps", ["antebrazos"], "elbow_flexion", ["maquina", "disco"], 1,
        "Codos fijos en el pad; sube sin balancear.",
        "Curl a discos con apoyo: bíceps sin impulso de hombro.",
        []),
    _ex("Curl predicador a placas (Etenon)", ["Curl predicador a placas"],
        "biceps", ["antebrazos"], "elbow_flexion", ["maquina", "banco_scott"], 1,
        "Extiende casi del todo abajo; sube sin despegar las axilas del pad.",
        "Predicador a placas: tensión continua, ideal para acercarse al fallo.",
        ["codo"]),
    _ex("Total Curl (Etenon)", ["Total Curl"],
        "biceps", ["antebrazos"], "elbow_flexion", ["maquina"], 1,
        "Recorrido completo con los codos alineados al eje de la máquina.",
        "Curl guiado de recorrido total: estiramiento y pico en la misma máquina.",
        []),

    # ============================ MAXPUMP ============================
    _ex("Press convergente de palanca (Maxpump)", ["Press convergente de palanca"],
        "pecho", ["triceps"], "horizontal_push", ["maquina", "disco"], 1,
        "Los agarres convergen al frente; aprieta el pecho al cierre.",
        "Convergente: sigue la línea natural de fibras del pectoral.",
        []),
    _ex("Remo alto (Maxpump)", ["Remo alto Maxpump"],
        "espalda", ["trapecio", "biceps"], "horizontal_pull", ["maquina"], 1,
        "Tira con los codos altos hacia atrás; junta escápulas.",
        "Remo alto: espalda alta y trapecio medio, postura y densidad.",
        []),
    _ex("Hack pendular (Maxpump)", ["Hack pendular", "Péndulo de sentadilla Maxpump"],
        "cuadriceps", ["gluteos"], "squat", ["maquina"], 1,
        "Baja profundo siguiendo el arco del péndulo; empuja con todo el pie.",
        "El arco pendular mantiene tensión constante y rodillas cómodas.",
        ["rodilla"]),
    _ex("Elevación de piernas (Maxpump)", ["Elevación de piernas en soporte"],
        "core", [], "core_flexion", ["maquina", "peso_corporal"], 1,
        "Antebrazos apoyados; sube las rodillas al pecho enrollando la pelvis.",
        "Flexión de cadera y tronco: abdomen inferior sin tracción lumbar.",
        []),
    _ex("Hip Thrust de pie (Maxpump)", ["Hip Thrust de pie"],
        "gluteos", ["isquios"], "hip_extension", ["maquina"], 1,
        "Empuja la palanca con la cadera hacia delante hasta bloquear.",
        "Extensión de cadera de pie: glúteo con setup rápido y sin barra.",
        []),
    _ex("Tríceps francés en polea (Maxpump)", ["Tríceps francés en polea"],
        "triceps", [], "elbow_extension", ["polea"], 1,
        "Codos fijos junto a la cabeza; extiende completo y controla la vuelta.",
        "Extensión sobre la cabeza en polea: cabeza larga con tensión continua.",
        ["codo"]),
    _ex("Curl bíceps horizontal (Maxpump)", ["Curl bíceps horizontal"],
        "biceps", [], "elbow_flexion", ["maquina"], 1,
        "Brazos apoyados en horizontal; sube sin despegar los codos.",
        "Curl con brazo horizontal: pico de tensión en el acortamiento.",
        []),
    _ex("Elevaciones laterales a discos (Maxpump)", ["Elevaciones laterales a discos"],
        "hombros", [], "shoulder_abduction", ["maquina", "disco"], 1,
        "Sube hasta la horizontal sin encoger; baja lento.",
        "Abducción a discos: deltoides medio con arranque suave.",
        []),

    # ===================== GLUTE BUILDER / PRIME =====================
    _ex("Extensiones de rodilla (Prime)", ["Extensiones de rodilla Prime"],
        "cuadriceps", [], "knee_extension", ["maquina"], 1,
        "Extiende hasta bloquear y aguanta 1 s; baja 3 s.",
        "Aislamiento de cuádriceps con perfiles de resistencia ajustables (Prime).",
        ["rodilla"]),
    _ex("Hip Thrust (Prime)", ["Hip Thrust Prime", "Glute Builder Hip Thrust"],
        "gluteos", ["isquios"], "hip_extension", ["maquina"], 1,
        "Extiende cadera hasta bloquear y aprieta el glúteo arriba.",
        "Hip thrust en máquina: setup rápido y sobrecarga progresiva cómoda.",
        []),
    _ex("Patada de glúteo (Prime)", ["Patada de glúteo Prime", "Glute Builder patada"],
        "gluteos", ["isquios"], "hip_extension", ["maquina"], 1,
        "Empuja con el talón hasta extender la cadera por completo.",
        "Patada guiada: glúteo mayor unilateral con tensión pico arriba.",
        []),
    _ex("Prensa horizontal (Prime)", ["Prensa horizontal Prime"],
        "cuadriceps", ["gluteos"], "squat", ["maquina"], 1,
        "Baja hasta 90º o más sin despegar la cadera; empuja con todo el pie.",
        "Prensa horizontal con perfiles de carga: piernas sin compresión axial.",
        ["rodilla"]),
    _ex("Sentadilla búlgara (Prime)", ["Sentadilla búlgara en máquina"],
        "cuadriceps", ["gluteos"], "lunge", ["maquina"], 2,
        "Pie trasero apoyado; baja vertical con el torso estable.",
        "Búlgara guiada: zancada profunda unilateral con equilibrio asistido.",
        ["rodilla"]),
    _ex("Hiperextensión de cadera con carga (Prime)", ["Hiperextensión de cadera con carga"],
        "gluteos", ["isquios", "espalda"], "hip_extension", ["maquina"], 1,
        "Bisagra desde la cadera con espalda neutra; sube con glúteo, no con lumbar.",
        "Extensión de cadera cargada: cadena posterior con columna protegida.",
        ["lumbar"]),
    _ex("Hiperextensión glúteo inversa (Prime)", ["Hiperextensión glúteo inversa"],
        "gluteos", ["isquios"], "hip_extension", ["maquina"], 2,
        "Torso fijo; eleva las piernas con glúteo sin arquear el lumbar.",
        "Inversa: glúteo/femoral descargando por completo la columna.",
        ["lumbar"]),
    _ex("Abducciones (Prime)", ["Abducciones Prime", "Glute Builder abducciones"],
        "gluteos", [], "hip_abduction", ["maquina"], 1,
        "Abre contra los pads inclinando el torso según el énfasis buscado.",
        "Abducción con perfil de carga regulable: glúteo medio y mayor superior.",
        []),
    _ex("V-Squat (Prime)", ["V-Squat", "Sentadilla V Prime"],
        "cuadriceps", ["gluteos"], "squat", ["maquina"], 1,
        "Espalda al respaldo; baja profundo y empuja con todo el pie.",
        "Sentadilla en V guiada: patrón profundo con torso soportado.",
        ["rodilla"]),

    # ============================ PLATINUM ============================
    _ex("Press militar en polea (Platinum)", ["Press militar en polea"],
        "hombros", ["triceps"], "vertical_push", ["polea"], 1,
        "Empuja vertical desde los hombros; core firme.",
        "Press de hombro a polea: tensión continua también abajo.",
        ["hombro"]),
    _ex("Pec Deck (Platinum)", ["Pec deck Platinum"],
        "pecho", [], "horizontal_push", ["maquina"], 1,
        "Junta los brazos en arco y aprieta 1 s en el centro.",
        "Aislamiento de pectoral en aducción con apoyo completo.",
        []),
    _ex("Femoral tumbado (Platinum)", ["Femoral tumbado Platinum"],
        "isquios", [], "knee_flexion", ["maquina"], 1,
        "Cadera pegada; flexiona al glúteo y baja lento.",
        "Flexión de rodilla tumbado: isquios aislados.",
        ["rodilla"]),
    _ex("Gemelo de pie (Platinum)", ["Gemelo de pie Platinum"],
        "gemelos", [], "plantar_flexion", ["maquina"], 1,
        "Estira bien abajo 1 s; sube de puntillas al máximo.",
        "Flexión plantar de pie: gastrocnemio con carga vertical guiada.",
        []),
    _ex("Multicadera (Platinum)", ["Multicadera", "Multicadera patada de glúteo"],
        "gluteos", ["aductores"], "hip_extension", ["maquina"], 1,
        "Rodillo en el muslo; patada atrás con la pelvis estable.",
        "Estación multicadera: extensión, abducción y aducción en una máquina.",
        []),

    # ============================ TUFF STUFF ============================
    _ex("Press convergente (Tuff Stuff)", ["Press convergente Tuff Stuff"],
        "pecho", ["triceps"], "horizontal_push", ["maquina"], 1,
        "Empuja convergiendo al frente; aprieta el pecho al cierre.",
        "Press convergente a placas: línea de fibras natural del pectoral.",
        []),
    _ex("Curl femoral (Tuff Stuff)", ["Curl femoral Tuff Stuff"],
        "isquios", [], "knee_flexion", ["maquina"], 1,
        "Flexiona hasta el máximo y controla la vuelta 3 s.",
        "Curl femoral a placas: isquios con carga estable.",
        ["rodilla"]),

    # ======================== MÁQUINAS SIN MARCA ========================
    _ex("Jalón supino de palanca", ["Jalón supino a palanca"],
        "espalda", ["biceps"], "vertical_pull", ["maquina", "disco"], 1,
        "Agarre supino; tira de los codos al costado con el pecho alto.",
        "El agarre supino añade bíceps y acentúa el dorsal bajo.",
        []),
    _ex("Remo alto de palanca a discos", ["Remo alto a discos"],
        "espalda", ["trapecio", "biceps"], "horizontal_pull", ["maquina", "disco"], 1,
        "Codos altos hacia atrás; junta escápulas al final.",
        "Remo alto de palanca: espalda alta y romboides con carga a discos.",
        []),
    _ex("Remo Dorian", ["Remo Dorian Yates"],
        "espalda", ["biceps", "trapecio"], "horizontal_pull", ["maquina", "disco"], 2,
        "Torso a unos 70º; tira de la barra al abdomen bajo con agarre supino.",
        "Remo estilo Yates: dorsal completo con menos exigencia lumbar que el remo libre.",
        ["lumbar"]),
    _ex("Pullover a discos", ["Máquina de pullover"],
        "espalda", ["pecho", "triceps"], "vertical_pull", ["maquina", "disco"], 1,
        "Brazos casi extendidos; lleva el arco desde arriba hasta las caderas.",
        "Pullover en máquina: dorsal en aislamiento puro sin sujetar el peso sobre la cara.",
        ["hombro"]),
    _ex("Press banca (estación)", ["Press banca a discos", "Press banca estación"],
        "pecho", ["triceps", "hombros"], "horizontal_push", ["maquina", "disco", "banco"], 1,
        "Escápulas retraídas; baja al pecho medio y empuja recto.",
        "Estación de press banca con recorrido asistido: cargar fuerte con seguridad.",
        ["hombro"]),
    _ex("Máquina Smith", ["Smith", "Multipower"],
        "cuadriceps", ["pecho", "hombros", "gluteos"], "squat", ["multipower"], 1,
        "Barra guiada: sirve para sentadilla, press, remo o hip thrust según el montaje.",
        "Multipower de barra guiada: patrón fijo para progresar seguro en básicos.",
        []),
    _ex("Hack Squat", ["Hack squat sin marca"],
        "cuadriceps", ["gluteos"], "squat", ["maquina", "disco"], 1,
        "Baja profundo con el lumbar pegado al respaldo.",
        "Hack squat clásica: cuádriceps dominante con torso soportado.",
        ["rodilla"]),
    _ex("Belt Squat", ["Sentadilla con cinturón"],
        "cuadriceps", ["gluteos"], "squat", ["maquina", "lastre"], 1,
        "Carga colgada del cinturón de cadera; sentadilla profunda con torso erguido.",
        "Toda la carga entra por la cadera: piernas fuertes sin compresión de columna.",
        []),
    _ex("Hip Thrust con cinturón", ["Hip thrust con cinturón"],
        "gluteos", ["isquios"], "hip_extension", ["maquina", "lastre"], 1,
        "Cinturón en la cadera; extiende hasta bloquear y aprieta arriba.",
        "Variante con cinturón: sin barra sobre la pelvis, más cómoda y rápida.",
        []),
    _ex("Femoral unilateral a discos", ["Curl femoral unilateral a discos"],
        "isquios", [], "knee_flexion", ["maquina", "disco"], 1,
        "Una pierna cada vez; flexiona completo y baja lento.",
        "Femoral unilateral: corrige asimetrías de la cadena posterior.",
        ["rodilla"]),
    _ex("Prensa convencional", ["Prensa de piernas convencional"],
        "cuadriceps", ["gluteos"], "squat", ["maquina", "disco"], 1,
        "Pies al ancho de cadera; baja sin despegar el lumbar y empuja completo.",
        "Prensa a 45º: el básico de pierna con carga alta y espalda apoyada.",
        ["rodilla"]),
    _ex("Prensa de palanca", ["Prensa de palanca a discos"],
        "cuadriceps", ["gluteos"], "squat", ["maquina", "disco"], 1,
        "Recorrido completo controlando la bajada.",
        "Prensa de palanca: curva de resistencia suave al arranque.",
        ["rodilla"]),
    _ex("Prensa horizontal", ["Prensa horizontal a placas"],
        "cuadriceps", ["gluteos"], "squat", ["maquina"], 1,
        "Empuja sin bloquear de golpe las rodillas; vuelta lenta.",
        "Prensa horizontal a placas: accesible y estable para todos los niveles.",
        ["rodilla"]),
    _ex("Elevaciones laterales asistidas (máquina)", ["Elevaciones laterales asistidas"],
        "hombros", [], "shoulder_abduction", ["maquina"], 1,
        "Los brazos siguen el carril de la máquina hasta la horizontal.",
        "Abducción asistida: deltoides medio sin trampa de trapecio.",
        []),
    _ex("Crunch tumbado (máquina)", ["Crunch tumbado"],
        "core", [], "core_flexion", ["maquina"], 1,
        "Encorva llevando las costillas a la pelvis; exhala al subir.",
        "Flexión de tronco tumbado con carga: recto abdominal progresable.",
        []),
    _ex("Crunch sentado (máquina)", ["Crunch sentado"],
        "core", [], "core_flexion", ["maquina"], 1,
        "Encorva contra la resistencia sin tirar del cuello.",
        "Crunch sentado a placas: abdomen con carga medible.",
        ["cuello"]),

    # ========================== ZONA DE CARDIO ==========================
    _ex("Cinta de correr", ["Cinta", "Treadmill"],
        "cardio", [], "cardio", ["maquina"], 1,
        "Ajusta velocidad e inclinación al objetivo (caminar en cuesta, rodaje, series).",
        "Cardio de impacto regulable: LISS en cuesta o HIIT en llano.",
        []),
    _ex("Air Bike", ["Assault bike", "Bicicleta de aire"],
        "cardio", [], "cardio", ["maquina"], 1,
        "Empuja y tira con brazos y piernas; ritmo constante o sprints.",
        "Resistencia por aire: intensidad ilimitada, ideal para intervalos.",
        []),
    _ex("Remo (cardio)", ["Máquina de remo", "Remoergómetro", "Rower"],
        "cardio", ["espalda"], "cardio", ["maquina"], 1,
        "Secuencia piernas-torso-brazos; vuelve en orden inverso sin encorvar.",
        "Cardio de cuerpo completo con tracción: gasto alto y sin impacto.",
        []),
    _ex("SkiErg", ["Ski erg"],
        "cardio", ["espalda", "core"], "cardio", ["maquina"], 1,
        "Tira de las cuerdas hacia abajo con bisagra de cadera; core firme.",
        "Patrón de esquí: tren superior y core sin impacto en piernas.",
        []),
    _ex("Escaleras", ["Escalador", "Stairmaster"],
        "cardio", ["gluteos", "cuadriceps"], "cardio", ["maquina"], 1,
        "Sube peldaños con el torso erguido, sin colgarte de las barandillas.",
        "Cardio en subida: gasto alto con estímulo extra de glúteo.",
        []),
    _ex("Bicicleta estática", ["Bici estática"],
        "cardio", [], "cardio", ["maquina"], 1,
        "Ajusta la altura del sillín a la cadera; cadencia cómoda.",
        "Cardio sin impacto: perfecto para LISS y recuperación activa.",
        []),
    _ex("Elíptica", ["Bicicleta elíptica"],
        "cardio", [], "cardio", ["maquina"], 1,
        "Zancada fluida empujando también con los brazos.",
        "Cuerpo completo sin impacto: gasto alto apto para cualquier nivel.",
        []),

    # ========================== MATERIAL LIBRE ==========================
    _ex("Empuje de trineo", ["Sled push", "Empujar trineo"],
        "cuadriceps", ["gluteos", "gemelos", "core"], "lunge", ["trineo"], 1,
        "Brazos firmes en las barras; empuja con pasos cortos y potentes.",
        "Solo concéntrico: piernas y capacidad de trabajo sin dolor muscular posterior.",
        []),
    _ex("Arrastre de trineo", ["Sled drag", "Arrastrar trineo"],
        "isquios", ["gluteos", "espalda"], "lunge", ["trineo"], 1,
        "Camina hacia atrás o de frente con la correa tensa y el torso firme.",
        "Arrastre: cadena posterior y acondicionamiento sin impacto.",
        []),
]
